# Generated by Django 3.0.8 on 2020-07-06 11:27

import django.core.files.storage
from django.db import migrations, models
import mysite.directory.models.model_teacher


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20, verbose_name='Room Number')),
                ('room_name', models.CharField(max_length=20, verbose_name='Room Name')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=20, unique=True, verbose_name='Subject ID')),
                ('subject_name', models.CharField(max_length=50, verbose_name='Subject Name')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.IntegerField(unique=True, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Name')),
                ('photo', models.ImageField(blank=True, max_length=200, null=True, storage=django.core.files.storage.FileSystemStorage(location='files'), upload_to=mysite.directory.models.model_teacher.upload_path_handler, verbose_name='Profile Picture')),
                ('email', models.CharField(editable=False, max_length=150, unique=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile Number')),
            ],
        ),
    ]
