# Generated by Django 3.0.8 on 2020-07-06 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='room_number',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='directory.Room', verbose_name='Room Number'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(default=0, limit_choices_to=5, to='directory.Subject', verbose_name='Subjects Taught'),
        ),
    ]
