# Generated by Django 3.1.5 on 2021-01-27 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_auto_20200706_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
