# Generated by Django 3.1.5 on 2021-01-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_room_subject_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(default='', max_length=10, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(default=0, to='directory.Subject', verbose_name='Subjects Taught'),
        ),
    ]
