# Generated by Django 3.1.5 on 2021-01-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_auto_20210127_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_id',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(to='directory.Subject', verbose_name='Subjects Taught'),
        ),
    ]
