# Generated by Django 3.1.5 on 2021-01-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_auto_20210128_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='Subject ID'),
        ),
    ]
