# Generated by Django 3.1.5 on 2021-01-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_auto_20210128_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Room Number'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Subject Name'),
        ),
    ]
